# This config is for the BACKEND service only

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
watchPatterns = ["hrms_backend/**"]

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 4"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
